package com.dbuyer.dao.domain;

public class MemberInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.member_id
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.descript
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String descript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.email
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.identif
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String identif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.lastlogin
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String lastlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.lastloginip
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String lastloginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.logincount
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String logincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.logourl
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String logourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.memberkind
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String memberkind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.password
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.phone
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.realcd
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String realcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.realnm
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String realnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.registtime
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String registtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.sex
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.status
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.regclient
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String regclient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.softKey
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    private String softkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.member_id
     *
     * @return the value of m_member.member_id
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.member_id
     *
     * @param memberId the value for m_member.member_id
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.descript
     *
     * @return the value of m_member.descript
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.descript
     *
     * @param descript the value for m_member.descript
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.email
     *
     * @return the value of m_member.email
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.email
     *
     * @param email the value for m_member.email
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.identif
     *
     * @return the value of m_member.identif
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getIdentif() {
        return identif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.identif
     *
     * @param identif the value for m_member.identif
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setIdentif(String identif) {
        this.identif = identif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.lastlogin
     *
     * @return the value of m_member.lastlogin
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.lastlogin
     *
     * @param lastlogin the value for m_member.lastlogin
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setLastlogin(String lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.lastloginip
     *
     * @return the value of m_member.lastloginip
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.lastloginip
     *
     * @param lastloginip the value for m_member.lastloginip
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.logincount
     *
     * @return the value of m_member.logincount
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.logincount
     *
     * @param logincount the value for m_member.logincount
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setLogincount(String logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.logourl
     *
     * @return the value of m_member.logourl
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.logourl
     *
     * @param logourl the value for m_member.logourl
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.memberkind
     *
     * @return the value of m_member.memberkind
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getMemberkind() {
        return memberkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.memberkind
     *
     * @param memberkind the value for m_member.memberkind
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setMemberkind(String memberkind) {
        this.memberkind = memberkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.password
     *
     * @return the value of m_member.password
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.password
     *
     * @param password the value for m_member.password
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.phone
     *
     * @return the value of m_member.phone
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.phone
     *
     * @param phone the value for m_member.phone
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.realcd
     *
     * @return the value of m_member.realcd
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getRealcd() {
        return realcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.realcd
     *
     * @param realcd the value for m_member.realcd
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setRealcd(String realcd) {
        this.realcd = realcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.realnm
     *
     * @return the value of m_member.realnm
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getRealnm() {
        return realnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.realnm
     *
     * @param realnm the value for m_member.realnm
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setRealnm(String realnm) {
        this.realnm = realnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.registtime
     *
     * @return the value of m_member.registtime
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.registtime
     *
     * @param registtime the value for m_member.registtime
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setRegisttime(String registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.sex
     *
     * @return the value of m_member.sex
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.sex
     *
     * @param sex the value for m_member.sex
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.status
     *
     * @return the value of m_member.status
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.status
     *
     * @param status the value for m_member.status
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.regclient
     *
     * @return the value of m_member.regclient
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getRegclient() {
        return regclient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.regclient
     *
     * @param regclient the value for m_member.regclient
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setRegclient(String regclient) {
        this.regclient = regclient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.softKey
     *
     * @return the value of m_member.softKey
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public String getSoftkey() {
        return softkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.softKey
     *
     * @param softkey the value for m_member.softKey
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    public void setSoftkey(String softkey) {
        this.softkey = softkey;
    }
}