package com.dbuyer.dao.mapper;

import com.dbuyer.dao.domain.MemberInfo;

public interface MemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    int insert(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    int insertSelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    MemberInfo selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    int updateByPrimaryKeySelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbg.generated Wed Aug 09 15:07:54 CST 2017
     */
    int updateByPrimaryKey(MemberInfo record);
}